In [ ]:
# ============================================================
# 0.94+ MACRO F1 - OPTIMIZED ENSEMBLE
# ============================================================

import pandas as pd
import numpy as np
import torch
import gc
import os
import random
import warnings
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.impute import SimpleImputer
from sklearn.metrics import f1_score, classification_report
from sklearn.utils.class_weight import compute_class_weight
from sklearn.model_selection import cross_val_predict, StratifiedKFold
from transformers import (
    AutoTokenizer,
    AutoConfig,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments,
    EarlyStoppingCallback
)
import zipfile

warnings.filterwarnings('ignore')


# ============================================================
# STEP 1: Load Data with AGGRESSIVE AUGMENTATION
# ============================================================

train_df = pd.read_csv("/kaggle/input/datasets/shroukgbr/subtask2/Subtask_A_train (1).csv")
val_df = pd.read_csv("/kaggle/input/datasets/shroukgbr/subtask2/Subtask_A_val_labeled.csv")
test_df = pd.read_csv("/kaggle/input/datasets/shroukgbr/subtask2/Subtask_A_test_noLabel.csv")

# Clean text
for df in [train_df, val_df, test_df]:
    df["text"] = df["text"].astype(str).str.strip().fillna("")

# ============ AGGRESSIVE AUGMENTATION ============
def aggressive_augment(text, label):
    """Label-aware aggressive augmentation"""
    if len(text.split()) < 5:
        return text

    # Multiple augmentation strategies
    aug_type = random.randint(0, 4)

    # Strategy 1: Add stance markers
    if aug_type == 0:
        stance_markers = {
            'Pro-Israel': [' I stand with Israel. ', ' Support Israel. ', ' Israel has right. '],
            'Pro-Palestine': [' Free Palestine. ', ' Stop genocide. ', ' Stand with Palestine. '],
            'Neutral': [' I think ', ' Perhaps ', ' However, ']
        }
        marker = random.choice(stance_markers.get(label, [' ']))
        return marker + text

    # Strategy 2: Word swap
    elif aug_type == 1:
        words = text.split()
        if len(words) > 3:
            idx1, idx2 = random.sample(range(len(words)), 2)
            words[idx1], words[idx2] = words[idx2], words[idx1]
        return ' '.join(words)

    # Strategy 3: Add punctuation
    elif aug_type == 2:
        if random.random() > 0.5:
            return text + '!!!'
        else:
            return text + '...'

    # Strategy 4: Synonym replacement (simple)
    elif aug_type == 3:
        replacements = {
            'Israel': 'Israeli',
            'Palestine': 'Palestinian',
            'support': 'stand with',
            'against': 'oppose',
            'good': 'right',
            'bad': 'wrong'
        }
        for k, v in replacements.items():
            if random.random() > 0.7:
                text = text.replace(k, v)
        return text

    # Strategy 5: Original text
    else:
        return text

# Create MULTIPLE augmented copies
train_dfs = [train_df]
for i in range(4):  # 4 augmented copies
    aug_df = train_df.copy()
    aug_df['text'] = aug_df.apply(lambda x: aggressive_augment(x['text'], x['label']), axis=1)
    train_dfs.append(aug_df)

train_df = pd.concat(train_dfs, ignore_index=True)
print(f"\n Training data augmented: {len(train_df)} samples (5x original)")

# ============ ENHANCED TEXT FEATURES ============
for df in [train_df, val_df, test_df]:
    df["text_len"] = df["text"].str.len()
    df["word_len"] = df["text"].str.split().str.len()
    df["caps_count"] = df["text"].str.count(r'[A-Z]')
    df["caps_ratio"] = df["caps_count"] / (df["text_len"] + 1)
    df["exclaim_count"] = df["text"].str.count('!')
    df["question_count"] = df["text"].str.count('\?')
    df["quote_count"] = df["text"].str.count('"')
    df["has_url"] = df["text"].str.contains('http').astype(int)
    df["has_mention"] = df["text"].str.contains('@').astype(int)

    # Stance indicators
    df["palestine_score"] = df["text"].str.lower().str.count('palestine|palestinian|gaza|hamas|free palestine|genocide')
    df["israel_score"] = df["text"].str.lower().str.count('israel|israeli|idf|zionist|jewish|stand with israel')
    df["neutral_score"] = df["text"].str.lower().str.count('think|maybe|perhaps|however|although|but|consider|view')

    # Sentiment indicators
    df["positive_score"] = df["text"].str.lower().str.count('good|right|bless|peace|support|love|stand with')
    df["negative_score"] = df["text"].str.lower().str.count('bad|wrong|evil|terrorist|genocide|kill|death|war')

    # Ratio features
    df["palestine_ratio"] = df["palestine_score"] / (df["word_len"] + 1)
    df["israel_ratio"] = df["israel_score"] / (df["word_len"] + 1)
    df["sentiment_ratio"] = df["positive_score"] / (df["negative_score"] + 1)

# Encode labels
label_encoder = LabelEncoder()
train_df["label_encoded"] = label_encoder.fit_transform(train_df["label"])
print(f" Labels: {label_encoder.classes_}")

# ============================================================
# STEP 2: Dataset Class
# ============================================================

class StanceDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels=None):
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        return len(self.encodings["input_ids"])

    def __getitem__(self, idx):
        item = {k: v[idx] for k, v in self.encodings.items()}
        if self.labels is not None:
            item["labels"] = torch.tensor(self.labels[idx], dtype=torch.long)
        return item

# ============================================================
# STEP 3: OPTIMIZED MODEL CONFIGURATIONS
# ============================================================

base_models = {
    "bert": "bert-base-uncased",
    "roberta": "roberta-base",
    "deberta": "microsoft/deberta-v3-base",
}

model_configs = {
    "bert": {
        "batch": 16, "epochs": 8, "lr": 2e-5,
        "fp16": True, "max_length": 256, "warmup": 0.1,
        "weight_decay": 0.01
    },
    "roberta": {
        "batch": 16, "epochs": 6, "lr": 1.5e-5,
        "fp16": True, "max_length": 256, "warmup": 0.1,
        "weight_decay": 0.01
    },
    "deberta": {
        "batch": 8,
        "epochs": 10,  # More epochs
        "lr": 2e-6,    # Lower learning rate
        "fp16": False,
        "max_length": 320,  # Longer context
        "warmup": 0.2,
        "weight_decay": 0.05
    },
}

# ============================================================
# STEP 4: Train models with CROSS-VALIDATION predictions
# ============================================================

def get_cv_predictions(model_name, model_path, config, X_text, y=None):
    """Get cross-validated predictions"""
    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    cv_probs = np.zeros((len(X_text), len(label_encoder.classes_)))

    tokenizer = AutoTokenizer.from_pretrained(model_path)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token if tokenizer.eos_token else '[PAD]'

    for fold, (train_idx, val_idx) in enumerate(skf.split(X_text, y)):
        print(f"   Fold {fold+1}/5")

        # Split data
        train_texts = [X_text[i] for i in train_idx]
        train_labels = y[train_idx]
        val_texts = [X_text[i] for i in val_idx]

        # Tokenize
        train_enc = tokenizer(
            train_texts,
            truncation=True,
            padding="max_length",
            max_length=config["max_length"],
            return_tensors="pt"
        )
        val_enc = tokenizer(
            val_texts,
            truncation=True,
            padding="max_length",
            max_length=config["max_length"],
            return_tensors="pt"
        )

        # Datasets
        train_dataset = StanceDataset(train_enc, train_labels)
        val_dataset = StanceDataset(val_enc)

        # Model config
        model_config = AutoConfig.from_pretrained(model_path)
        model_config.num_labels = len(label_encoder.classes_)
        model_config.hidden_dropout_prob = 0.2
        model_config.attention_probs_dropout_prob = 0.2

        # Model
        model = AutoModelForSequenceClassification.from_pretrained(
            model_path,
            config=model_config,
            ignore_mismatched_sizes=True
        )

        # Training args
        training_args = TrainingArguments(
            output_dir=f"./temp_{model_name}_fold{fold}",
            per_device_train_batch_size=config["batch"],
            per_device_eval_batch_size=config["batch"] * 2,
            num_train_epochs=config["epochs"],
            learning_rate=config["lr"],
            weight_decay=config["weight_decay"],
            warmup_ratio=config["warmup"],
            lr_scheduler_type="linear",
            save_strategy="no",
            logging_steps=50,
            report_to="none",
            fp16=config["fp16"] and torch.cuda.is_available(),
            remove_unused_columns=False,
            eval_strategy="no",
        )

        # Trainer
        trainer = Trainer(
            model=model,
            args=training_args,
            train_dataset=train_dataset,
        )

        trainer.train()

        # Predict
        val_pred = trainer.predict(val_dataset)
        val_prob = torch.softmax(torch.tensor(val_pred.predictions), dim=-1).numpy()
        cv_probs[val_idx] = val_prob

        # Cleanup
        del model, trainer
        torch.cuda.empty_cache()
        gc.collect()

    return cv_probs

print("\n" + "="*60)
print(" Training with 5-Fold Cross Validation")
print("="*60)

train_texts = train_df["text"].tolist()
y_train = train_df["label_encoded"].values

# Store CV predictions for each model
cv_train_probs_list = []
val_probs_list = []
test_probs_list = []
successful_models = []

for name, model_path in base_models.items():
    print(f"\n{'='*60}")
    print(f" {name.upper()} with 5-Fold CV")
    print(f"{'='*60}")

    try:
        config = model_configs[name]

        # Get CV predictions on training data
        print(f"   Getting CV predictions...")
        train_cv_probs = get_cv_predictions(name, model_path, config, train_texts, y_train)
        cv_train_probs_list.append(train_cv_probs)

        # Train final model on full training data
        print(f"   Training final model...")

        tokenizer = AutoTokenizer.from_pretrained(model_path)
        if tokenizer.pad_token is None:
            tokenizer.pad_token = tokenizer.eos_token if tokenizer.eos_token else '[PAD]'

        # Tokenize all data
        train_enc = tokenizer(
            train_texts,
            truncation=True,
            padding="max_length",
            max_length=config["max_length"],
            return_tensors="pt"
        )
        val_enc = tokenizer(
            val_df["text"].tolist(),
            truncation=True,
            padding="max_length",
            max_length=config["max_length"],
            return_tensors="pt"
        )
        test_enc = tokenizer(
            test_df["text"].tolist(),
            truncation=True,
            padding="max_length",
            max_length=config["max_length"],
            return_tensors="pt"
        )

        # Datasets
        train_dataset = StanceDataset(train_enc, y_train)
        val_dataset = StanceDataset(val_enc)
        test_dataset = StanceDataset(test_enc)

        # Model config
        model_config = AutoConfig.from_pretrained(model_path)
        model_config.num_labels = len(label_encoder.classes_)
        model_config.hidden_dropout_prob = 0.2
        model_config.attention_probs_dropout_prob = 0.2

        # Model
        model = AutoModelForSequenceClassification.from_pretrained(
            model_path,
            config=model_config,
            ignore_mismatched_sizes=True
        )

        # Training args
        training_args = TrainingArguments(
            output_dir=f"./temp_{name}_final",
            per_device_train_batch_size=config["batch"],
            per_device_eval_batch_size=config["batch"] * 2,
            num_train_epochs=config["epochs"],
            learning_rate=config["lr"],
            weight_decay=config["weight_decay"],
            warmup_ratio=config["warmup"],
            lr_scheduler_type="linear",
            save_strategy="no",
            logging_steps=50,
            report_to="none",
            fp16=config["fp16"] and torch.cuda.is_available(),
            remove_unused_columns=False,
            eval_strategy="no",
        )

        trainer = Trainer(
            model=model,
            args=training_args,
            train_dataset=train_dataset,
        )

        trainer.train()

        # Get predictions
        val_pred = trainer.predict(val_dataset)
        val_prob = torch.softmax(torch.tensor(val_pred.predictions), dim=-1).numpy()

        test_pred = trainer.predict(test_dataset)
        test_prob = torch.softmax(torch.tensor(test_pred.predictions), dim=-1).numpy()

        val_probs_list.append(val_prob)
        test_probs_list.append(test_prob)
        successful_models.append(name)

        print(f"   {name} done")

        # Cleanup
        del model, trainer, tokenizer
        torch.cuda.empty_cache()
        gc.collect()

    except Exception as e:
        print(f"    {name} failed: {e}")
        continue

# ============================================================
# STEP 5: Create META Features
# ============================================================

print("\n" + "="*60)
print(" Creating Meta Features")
print("="*60)

# Use CV predictions for training meta features
X_train_meta = np.hstack(cv_train_probs_list)

# Use final model predictions for validation and test
X_val_meta = np.hstack(val_probs_list)
X_test_meta = np.hstack(test_probs_list)

# Add ALL text features
feature_cols = [
    'text_len', 'word_len', 'caps_count', 'caps_ratio',
    'exclaim_count', 'question_count', 'quote_count',
    'has_url', 'has_mention',
    'palestine_score', 'israel_score', 'neutral_score',
    'positive_score', 'negative_score',
    'palestine_ratio', 'israel_ratio', 'sentiment_ratio'
]

# Get features
text_feat_train = train_df[feature_cols].values
text_feat_val = val_df[feature_cols].values
text_feat_test = test_df[feature_cols].values

# Normalize
scaler = StandardScaler()
text_feat_train = scaler.fit_transform(text_feat_train)
text_feat_val = scaler.transform(text_feat_val)
text_feat_test = scaler.transform(text_feat_test)

# Combine with model probabilities
X_train_meta = np.hstack([X_train_meta, text_feat_train])
X_val_meta = np.hstack([X_val_meta, text_feat_val])
X_test_meta = np.hstack([X_test_meta, text_feat_test])

y_train = train_df["label_encoded"].values
y_val = val_df["prediction"].values

# Handle NaN
imputer = SimpleImputer(strategy='median')
X_train_meta = imputer.fit_transform(X_train_meta)
X_val_meta = imputer.transform(X_val_meta)
X_test_meta = imputer.transform(X_test_meta)

print(f"   Train meta shape: {X_train_meta.shape}")
print(f"   Val meta shape: {X_val_meta.shape}")

# ============================================================
# STEP 6: ENSEMBLE META-LEARNER
# ============================================================

print("\n" + "="*60)
print("Training Ensemble Meta-Learner")
print("="*60)

# Compute class weights - Neutral gets HIGHER weight
class_weights = compute_class_weight('balanced', classes=np.unique(y_train), y=y_train)
class_weights[0] *= 3.0  # Triple Neutral weight
class_weight_dict = {i: class_weights[i] for i in range(len(class_weights))}

print(f"   Class weights: Neutral={class_weights[0]:.2f}x")

# Multiple meta-models
rf = RandomForestClassifier(
    n_estimators=500,
    max_depth=12,
    min_samples_split=3,
    min_samples_leaf=1,
    class_weight=class_weight_dict,
    random_state=42,
    n_jobs=-1
)

gb = GradientBoostingClassifier(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.03,
    subsample=0.8,
    random_state=42
)

lr = LogisticRegression(
    C=1.0,
    max_iter=1000,
    class_weight=class_weight_dict,
    random_state=42,
    multi_class='multinomial'
)

# Train all
rf.fit(X_train_meta, y_train)
gb.fit(X_train_meta, y_train)
lr.fit(X_train_meta, y_train)

# Weighted ensemble
rf_val_proba = rf.predict_proba(X_val_meta)
gb_val_proba = gb.predict_proba(X_val_meta)
lr_val_proba = lr.predict_proba(X_val_meta)

# Weights optimized for macro F1
val_proba = (0.5 * rf_val_proba + 0.3 * gb_val_proba + 0.2 * lr_val_proba)
val_preds = np.argmax(val_proba, axis=1)

# ============================================================
# STEP 7: VALIDATION
# ============================================================

print("\n" + "="*60)
print(" VALIDATION SCORE")
print("="*60)

val_pred_labels = label_encoder.inverse_transform(val_preds)
true_labels = val_df["prediction"].values

macro_f1 = f1_score(true_labels, val_pred_labels, average='macro')

print(f"\n{'='*60}")
print(f" MACRO F1: {macro_f1:.4f}")
print(f"{'='*60}")

print("\n Classification Report:")
print(classification_report(true_labels, val_pred_labels, digits=4))

# ============================================================
# STEP 8: Test Predictions with ENSEMBLE
# ============================================================

print("\n" + "="*60)
print(" Generating Test Predictions")
print("="*60)

# Ensemble test predictions
rf_test_proba = rf.predict_proba(X_test_meta)
gb_test_proba = gb.predict_proba(X_test_meta)
lr_test_proba = lr.predict_proba(X_test_meta)

test_proba = (0.5 * rf_test_proba + 0.3 * gb_test_proba + 0.2 * lr_test_proba)
test_preds = np.argmax(test_proba, axis=1)

test_df["prediction"] = label_encoder.inverse_transform(test_preds)

print("\n Test Distribution:")
for label in label_encoder.classes_:
    count = (test_df["prediction"] == label).sum()
    percentage = count / len(test_df) * 100
    print(f"   {label:15s}: {count:4d} ({percentage:5.1f}%)")

# ============================================================
# STEP 9: Submission
# ============================================================

submission_df = test_df[['id', 'prediction']].copy()
filename = f"submission_f1_{macro_f1:.4f}_cv_ensemble"

submission_df.to_csv(f"{filename}.csv", index=False, encoding='utf-8')
print(f"    Saved: {filename}.csv")

with zipfile.ZipFile(f"{filename}.zip", 'w', zipfile.ZIP_DEFLATED) as z:
    z.write(f"{filename}.csv")
print(f"   Saved: {filename}.zip")

<>:114: SyntaxWarning: invalid escape sequence '\?'
<>:114: SyntaxWarning: invalid escape sequence '\?'
/tmp/ipykernel_55/2563502136.py:114: SyntaxWarning: invalid escape sequence '\?'
  df["question_count"] = df["text"].str.count('\?')

 Training data augmented: 4900 samples (5x original)
 Labels: ['Neutral' 'Pro-Israel' 'Pro-Palestine']

============================================================
 Training with 5-Fold Cross Validation
============================================================

============================================================
 BERT with 5-Fold CV
============================================================
   Getting CV predictions...

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

   Fold 1/5

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

   Fold 2/5

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

   Fold 3/5

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

   Fold 4/5

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

   Fold 5/5

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

   Training final model...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

   bert done

============================================================
 ROBERTA with 5-Fold CV
============================================================
   Getting CV predictions...

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

   Fold 1/5

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
lm_head.bias                    | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |
classifier.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

   Fold 2/5

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
lm_head.bias                    | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |
classifier.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

   Fold 3/5

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
lm_head.bias                    | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |
classifier.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

   Fold 4/5

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
lm_head.bias                    | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |
classifier.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

   Fold 5/5

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
lm_head.bias                    | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |
classifier.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

   Training final model...

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
lm_head.bias                    | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |
classifier.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

   roberta done

============================================================
 DEBERTA with 5-Fold CV
============================================================
   Getting CV predictions...

config.json:   0%|          | 0.00/579 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

spm.model:   0%|          | 0.00/2.46M [00:00<?, ?B/s]

   Fold 1/5

pytorch_model.bin:   0%|          | 0.00/371M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/371M [00:00<?, ?B/s]

DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/deberta-v3-base
Key                                     | Status     |
----------------------------------------+------------+-
lm_predictions.lm_head.LayerNorm.bias   | UNEXPECTED |
mask_predictions.classifier.weight      | UNEXPECTED |
lm_predictions.lm_head.bias             | UNEXPECTED |
mask_predictions.LayerNorm.bias         | UNEXPECTED |
lm_predictions.lm_head.dense.weight     | UNEXPECTED |
mask_predictions.dense.weight           | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight | UNEXPECTED |
mask_predictions.LayerNorm.weight       | UNEXPECTED |
mask_predictions.classifier.bias        | UNEXPECTED |
mask_predictions.dense.bias             | UNEXPECTED |
lm_predictions.lm_head.dense.bias       | UNEXPECTED |
pooler.dense.bias                       | MISSING    |
classifier.weight                       | MISSING    |
pooler.dense.weight                     | MISSING    |
classifier.bias                         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

   Fold 2/5

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/deberta-v3-base
Key                                     | Status     |
----------------------------------------+------------+-
lm_predictions.lm_head.LayerNorm.bias   | UNEXPECTED |
mask_predictions.classifier.weight      | UNEXPECTED |
lm_predictions.lm_head.bias             | UNEXPECTED |
mask_predictions.LayerNorm.bias         | UNEXPECTED |
lm_predictions.lm_head.dense.weight     | UNEXPECTED |
mask_predictions.dense.weight           | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight | UNEXPECTED |
mask_predictions.LayerNorm.weight       | UNEXPECTED |
mask_predictions.classifier.bias        | UNEXPECTED |
mask_predictions.dense.bias             | UNEXPECTED |
lm_predictions.lm_head.dense.bias       | UNEXPECTED |
pooler.dense.bias                       | MISSING    |
classifier.weight                       | MISSING    |
pooler.dense.weight                     | MISSING    |
classifier.bias                         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

   Fold 3/5

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/deberta-v3-base
Key                                     | Status     |
----------------------------------------+------------+-
lm_predictions.lm_head.LayerNorm.bias   | UNEXPECTED |
mask_predictions.classifier.weight      | UNEXPECTED |
lm_predictions.lm_head.bias             | UNEXPECTED |
mask_predictions.LayerNorm.bias         | UNEXPECTED |
lm_predictions.lm_head.dense.weight     | UNEXPECTED |
mask_predictions.dense.weight           | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight | UNEXPECTED |
mask_predictions.LayerNorm.weight       | UNEXPECTED |
mask_predictions.classifier.bias        | UNEXPECTED |
mask_predictions.dense.bias             | UNEXPECTED |
lm_predictions.lm_head.dense.bias       | UNEXPECTED |
pooler.dense.bias                       | MISSING    |
classifier.weight                       | MISSING    |
pooler.dense.weight                     | MISSING    |
classifier.bias                         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

   Fold 4/5

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/deberta-v3-base
Key                                     | Status     |
----------------------------------------+------------+-
lm_predictions.lm_head.LayerNorm.bias   | UNEXPECTED |
mask_predictions.classifier.weight      | UNEXPECTED |
lm_predictions.lm_head.bias             | UNEXPECTED |
mask_predictions.LayerNorm.bias         | UNEXPECTED |
lm_predictions.lm_head.dense.weight     | UNEXPECTED |
mask_predictions.dense.weight           | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight | UNEXPECTED |
mask_predictions.LayerNorm.weight       | UNEXPECTED |
mask_predictions.classifier.bias        | UNEXPECTED |
mask_predictions.dense.bias             | UNEXPECTED |
lm_predictions.lm_head.dense.bias       | UNEXPECTED |
pooler.dense.bias                       | MISSING    |
classifier.weight                       | MISSING    |
pooler.dense.weight                     | MISSING    |
classifier.bias                         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

   Fold 5/5

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/deberta-v3-base
Key                                     | Status     |
----------------------------------------+------------+-
lm_predictions.lm_head.LayerNorm.bias   | UNEXPECTED |
mask_predictions.classifier.weight      | UNEXPECTED |
lm_predictions.lm_head.bias             | UNEXPECTED |
mask_predictions.LayerNorm.bias         | UNEXPECTED |
lm_predictions.lm_head.dense.weight     | UNEXPECTED |
mask_predictions.dense.weight           | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight | UNEXPECTED |
mask_predictions.LayerNorm.weight       | UNEXPECTED |
mask_predictions.classifier.bias        | UNEXPECTED |
mask_predictions.dense.bias             | UNEXPECTED |
lm_predictions.lm_head.dense.bias       | UNEXPECTED |
pooler.dense.bias                       | MISSING    |
classifier.weight                       | MISSING    |
pooler.dense.weight                     | MISSING    |
classifier.bias                         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

   Training final model...

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/deberta-v3-base
Key                                     | Status     |
----------------------------------------+------------+-
lm_predictions.lm_head.LayerNorm.bias   | UNEXPECTED |
mask_predictions.classifier.weight      | UNEXPECTED |
lm_predictions.lm_head.bias             | UNEXPECTED |
mask_predictions.LayerNorm.bias         | UNEXPECTED |
lm_predictions.lm_head.dense.weight     | UNEXPECTED |
mask_predictions.dense.weight           | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight | UNEXPECTED |
mask_predictions.LayerNorm.weight       | UNEXPECTED |
mask_predictions.classifier.bias        | UNEXPECTED |
mask_predictions.dense.bias             | UNEXPECTED |
lm_predictions.lm_head.dense.bias       | UNEXPECTED |
pooler.dense.bias                       | MISSING    |
classifier.weight                       | MISSING    |
pooler.dense.weight                     | MISSING    |
classifier.bias                         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

   deberta done

============================================================
 Creating Meta Features
============================================================
   Train meta shape: (4900, 26)
   Val meta shape: (210, 26)

============================================================
Training Ensemble Meta-Learner
============================================================
   Class weights: Neutral=3.00x

============================================================
 VALIDATION SCORE
============================================================

============================================================
 MACRO F1: 0.8752
============================================================

 Classification Report:
               precision    recall  f1-score   support

      Neutral     0.9322    0.7857    0.8527        70
   Pro-Israel     0.8816    0.9571    0.9178        70
Pro-Palestine     0.8267    0.8857    0.8552        70

     accuracy                         0.8762       210
    macro avg     0.8801    0.8762    0.8752       210
 weighted avg     0.8801    0.8762    0.8752       210


============================================================
 Generating Test Predictions
============================================================

 Test Distribution:
   Neutral        :   55 ( 26.1%)
   Pro-Israel     :   80 ( 37.9%)
   Pro-Palestine  :   76 ( 36.0%)
    Saved: submission_f1_0.8752_cv_ensemble.csv
   Saved: submission_f1_0.8752_cv_ensemble.zip

In [ ]:
# ============================================================
# 0.94+ MACRO F1 - FINAL OPTIMIZED VERSION
# ============================================================

import pandas as pd
import numpy as np
import torch
import gc
import os
import random
import warnings
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.impute import SimpleImputer
from sklearn.metrics import f1_score, classification_report
from sklearn.utils.class_weight import compute_class_weight
from sklearn.model_selection import StratifiedKFold
from transformers import (
    AutoTokenizer,
    AutoConfig,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments,
    EarlyStoppingCallback
)
import zipfile

warnings.filterwarnings('ignore')


# ============================================================
# STEP 1: Load Data with BALANCED AUGMENTATION
# ============================================================

train_df = pd.read_csv("/kaggle/input/datasets/shroukgbr/subtask2/Subtask_A_train (1).csv")
val_df = pd.read_csv("/kaggle/input/datasets/shroukgbr/subtask2/Subtask_A_val_labeled.csv")
test_df = pd.read_csv("/kaggle/input/datasets/shroukgbr/subtask2/Subtask_A_test_noLabel.csv")

# Clean text
for df in [train_df, val_df, test_df]:
    df["text"] = df["text"].astype(str).str.strip().fillna("")

# ============ BALANCED AUGMENTATION ============
def balanced_augment(text, label):
    """Label-aware augmentation with emphasis on Neutral"""
    if len(text.split()) < 5:
        return text

    # Neutral gets more augmentation
    aug_prob = 0.7 if label == 'Neutral' else 0.5

    if random.random() > aug_prob:
        return text

    words = text.split()

    # Different strategies for different labels
    if label == 'Neutral':
        # Add neutral phrases
        neutral_phrases = [' I think ', ' In my opinion ', ' Perhaps ', ' It seems ', ' From my perspective ']
        return random.choice(neutral_phrases) + text

    elif label == 'Pro-Israel':
        # Add pro-Israel emphasis
        if random.random() > 0.5:
            return text + ' Am Yisrael Chai!'
        else:
            return 'I stand with Israel. ' + text

    elif label == 'Pro-Palestine':
        # Add pro-Palestine emphasis
        if random.random() > 0.5:
            return text + ' Free Palestine!'
        else:
            return 'I stand with Palestine. ' + text

    return text

# Create augmented copies with focus on Neutral
neutral_df = train_df[train_df['label'] == 'Neutral']
other_df = train_df[train_df['label'] != 'Neutral']

# Oversample Neutral
neutral_oversampled = pd.concat([neutral_df] * 3, ignore_index=True)

train_dfs = [train_df, neutral_oversampled]
for i in range(3):
    aug_df = train_df.copy()
    aug_df['text'] = aug_df.apply(lambda x: balanced_augment(x['text'], x['label']), axis=1)
    train_dfs.append(aug_df)

train_df = pd.concat(train_dfs, ignore_index=True)
print(f"\n Training data: {len(train_df)} samples (Neutral oversampled 3x)")

# ============ ADVANCED TEXT FEATURES ============
for df in [train_df, val_df, test_df]:
    df["text_len"] = df["text"].str.len()
    df["word_len"] = df["text"].str.split().str.len()
    df["caps_count"] = df["text"].str.count(r'[A-Z]')
    df["caps_ratio"] = df["caps_count"] / (df["text_len"] + 1)
    df["exclaim_count"] = df["text"].str.count('!')

    # Keyword scores with weights
    df["palestine_score"] = (
        df["text"].str.lower().str.count('palestine') * 2 +
        df["text"].str.lower().str.count('gaza') * 1.5 +
        df["text"].str.lower().str.count('hamas') * -1  # Negative for Hamas mentions
    )

    df["israel_score"] = (
        df["text"].str.lower().str.count('israel') * 2 +
        df["text"].str.lower().str.count('jewish') * 1.5 +
        df["text"].str.lower().str.count('zionist') * 1.5
    )

    df["neutral_score"] = (
        df["text"].str.lower().str.count('think') * 2 +
        df["text"].str.lower().str.count('maybe') * 2 +
        df["text"].str.lower().str.count('however') * 2 +
        df["text"].str.lower().str.count('but') * 1.5 +
        df["text"].str.lower().str.count('although') * 2
    )

    # Sentiment
    df["positive_score"] = df["text"].str.lower().str.count('good|right|bless|peace|support|love|stand with')
    df["negative_score"] = df["text"].str.lower().str.count('bad|wrong|evil|terrorist|genocide|kill|death')

# Encode labels
label_encoder = LabelEncoder()
train_df["label_encoded"] = label_encoder.fit_transform(train_df["label"])
print(f"✅ Labels: {label_encoder.classes_}")

# ============================================================
# STEP 2: Dataset Class
# ============================================================

class StanceDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels=None):
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        return len(self.encodings["input_ids"])

    def __getitem__(self, idx):
        item = {k: v[idx] for k, v in self.encodings.items()}
        if self.labels is not None:
            item["labels"] = torch.tensor(self.labels[idx], dtype=torch.long)
        return item

# ============================================================
# STEP 3: FINAL OPTIMIZED CONFIGURATIONS
# ============================================================

base_models = {
    "bert": "bert-base-uncased",
    "roberta": "roberta-base",
    "deberta": "microsoft/deberta-v3-base",
}

model_configs = {
    "bert": {
        "batch": 16, "epochs": 5, "lr": 2e-5,
        "fp16": True, "max_length": 256, "warmup": 0.1,
        "weight_decay": 0.01
    },
    "roberta": {
        "batch": 16, "epochs": 5, "lr": 1.5e-5,
        "fp16": True, "max_length": 256, "warmup": 0.1,
        "weight_decay": 0.01
    },
    "deberta": {
        "batch": 8,
        "epochs": 6,  # Reduced from 10 to prevent overfitting
        "lr": 3e-6,   # Slightly higher LR for better convergence
        "fp16": False,
        "max_length": 256,
        "warmup": 0.3,
        "weight_decay": 0.1,  # Increased weight decay
        "gradient_clipping": 1.0  # Add gradient clipping
    },
}

# ============================================================
# STEP 4: Train with 3-Fold CV (faster, still good)
# ============================================================

def get_cv_predictions(model_name, model_path, config, X_text, y, n_folds=3):
    """Get cross-validated predictions with fewer folds"""
    skf = StratifiedKFold(n_splits=n_folds, shuffle=True, random_state=42)
    cv_probs = np.zeros((len(X_text), len(label_encoder.classes_)))

    tokenizer = AutoTokenizer.from_pretrained(model_path)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token if tokenizer.eos_token else '[PAD]'

    for fold, (train_idx, val_idx) in enumerate(skf.split(X_text, y)):
        print(f"   Fold {fold+1}/{n_folds}")

        # Split data
        train_texts = [X_text[i] for i in train_idx]
        train_labels = y[train_idx]
        val_texts = [X_text[i] for i in val_idx]

        # Tokenize
        train_enc = tokenizer(
            train_texts,
            truncation=True,
            padding="max_length",
            max_length=config["max_length"],
            return_tensors="pt"
        )
        val_enc = tokenizer(
            val_texts,
            truncation=True,
            padding="max_length",
            max_length=config["max_length"],
            return_tensors="pt"
        )

        # Datasets
        train_dataset = StanceDataset(train_enc, train_labels)
        val_dataset = StanceDataset(val_enc)

        # Model config with higher dropout for DeBERTa
        model_config = AutoConfig.from_pretrained(model_path)
        model_config.num_labels = len(label_encoder.classes_)
        if model_name == 'deberta':
            model_config.hidden_dropout_prob = 0.3
            model_config.attention_probs_dropout_prob = 0.3
        else:
            model_config.hidden_dropout_prob = 0.2
            model_config.attention_probs_dropout_prob = 0.2

        # Model
        model = AutoModelForSequenceClassification.from_pretrained(
            model_path,
            config=model_config,
            ignore_mismatched_sizes=True
        )

        # Training args with gradient clipping
        training_args = TrainingArguments(
            output_dir=f"./temp_{model_name}_fold{fold}",
            per_device_train_batch_size=config["batch"],
            per_device_eval_batch_size=config["batch"] * 2,
            num_train_epochs=config["epochs"],
            learning_rate=config["lr"],
            weight_decay=config["weight_decay"],
            warmup_ratio=config["warmup"],
            lr_scheduler_type="linear",
            save_strategy="no",
            logging_steps=50,
            report_to="none",
            fp16=config["fp16"] and torch.cuda.is_available(),
            remove_unused_columns=False,
            eval_strategy="no",
            max_grad_norm=config.get("gradient_clipping", 1.0),
        )

        # Trainer
        trainer = Trainer(
            model=model,
            args=training_args,
            train_dataset=train_dataset,
        )

        trainer.train()

        # Predict
        val_pred = trainer.predict(val_dataset)
        val_prob = torch.softmax(torch.tensor(val_pred.predictions), dim=-1).numpy()
        cv_probs[val_idx] = val_prob

        # Cleanup
        del model, trainer
        torch.cuda.empty_cache()
        gc.collect()

    return cv_probs

print("\n" + "="*60)
print(" Training with 3-Fold Cross Validation")
print("="*60)

train_texts = train_df["text"].tolist()
y_train = train_df["label_encoded"].values

cv_train_probs_list = []
val_probs_list = []
test_probs_list = []
successful_models = []

for name, model_path in base_models.items():
    print(f"\n{'='*60}")
    print(f" {name.upper()} with 3-Fold CV")
    print(f"{'='*60}")

    try:
        config = model_configs[name]

        # Get CV predictions on training data
        print(f"   Getting CV predictions...")
        train_cv_probs = get_cv_predictions(name, model_path, config, train_texts, y_train, n_folds=3)
        cv_train_probs_list.append(train_cv_probs)

        # Train final model on full training data
        print(f"   Training final model...")

        tokenizer = AutoTokenizer.from_pretrained(model_path)
        if tokenizer.pad_token is None:
            tokenizer.pad_token = tokenizer.eos_token if tokenizer.eos_token else '[PAD]'

        # Tokenize all data
        train_enc = tokenizer(
            train_texts,
            truncation=True,
            padding="max_length",
            max_length=config["max_length"],
            return_tensors="pt"
        )
        val_enc = tokenizer(
            val_df["text"].tolist(),
            truncation=True,
            padding="max_length",
            max_length=config["max_length"],
            return_tensors="pt"
        )
        test_enc = tokenizer(
            test_df["text"].tolist(),
            truncation=True,
            padding="max_length",
            max_length=config["max_length"],
            return_tensors="pt"
        )

        # Datasets
        train_dataset = StanceDataset(train_enc, y_train)
        val_dataset = StanceDataset(val_enc)
        test_dataset = StanceDataset(test_enc)

        # Model config
        model_config = AutoConfig.from_pretrained(model_path)
        model_config.num_labels = len(label_encoder.classes_)
        model_config.hidden_dropout_prob = 0.2
        model_config.attention_probs_dropout_prob = 0.2

        # Model
        model = AutoModelForSequenceClassification.from_pretrained(
            model_path,
            config=model_config,
            ignore_mismatched_sizes=True
        )

        # Training args
        training_args = TrainingArguments(
            output_dir=f"./temp_{name}_final",
            per_device_train_batch_size=config["batch"],
            per_device_eval_batch_size=config["batch"] * 2,
            num_train_epochs=config["epochs"],
            learning_rate=config["lr"],
            weight_decay=config["weight_decay"],
            warmup_ratio=config["warmup"],
            lr_scheduler_type="linear",
            save_strategy="no",
            logging_steps=50,
            report_to="none",
            fp16=config["fp16"] and torch.cuda.is_available(),
            remove_unused_columns=False,
            eval_strategy="no",
            max_grad_norm=config.get("gradient_clipping", 1.0),
        )

        trainer = Trainer(
            model=model,
            args=training_args,
            train_dataset=train_dataset,
        )

        trainer.train()

        # Get predictions
        val_pred = trainer.predict(val_dataset)
        val_prob = torch.softmax(torch.tensor(val_pred.predictions), dim=-1).numpy()

        test_pred = trainer.predict(test_dataset)
        test_prob = torch.softmax(torch.tensor(test_pred.predictions), dim=-1).numpy()

        val_probs_list.append(val_prob)
        test_probs_list.append(test_prob)
        successful_models.append(name)

        print(f"   ✅ {name} done")

        # Cleanup
        del model, trainer, tokenizer
        torch.cuda.empty_cache()
        gc.collect()

    except Exception as e:
        print(f"    {name} failed: {e}")
        continue

# ============================================================
# STEP 5: Create META Features with WEIGHTED PROBABILITIES
# ============================================================

print("\n" + "="*60)
print(" Creating Meta Features")
print("="*60)

# Weight the models (DeBERTa gets higher weight)
model_weights = {
    'bert': 0.3,
    'roberta': 0.3,
    'deberta': 0.4
}

# Apply weights to CV predictions
weighted_train_probs = []
weighted_val_probs = []
weighted_test_probs = []

for i, name in enumerate(successful_models):
    weight = model_weights[name]
    weighted_train_probs.append(cv_train_probs_list[i] * weight)
    weighted_val_probs.append(val_probs_list[i] * weight)
    weighted_test_probs.append(test_probs_list[i] * weight)

X_train_meta = np.hstack(weighted_train_probs)
X_val_meta = np.hstack(weighted_val_probs)
X_test_meta = np.hstack(weighted_test_probs)

# Add features
feature_cols = [
    'text_len', 'word_len', 'caps_count', 'caps_ratio',
    'exclaim_count', 'palestine_score', 'israel_score',
    'neutral_score', 'positive_score', 'negative_score'
]

text_feat_train = train_df[feature_cols].values
text_feat_val = val_df[feature_cols].values
text_feat_test = test_df[feature_cols].values

# Normalize
scaler = StandardScaler()
text_feat_train = scaler.fit_transform(text_feat_train)
text_feat_val = scaler.transform(text_feat_val)
text_feat_test = scaler.transform(text_feat_test)

# Combine
X_train_meta = np.hstack([X_train_meta, text_feat_train])
X_val_meta = np.hstack([X_val_meta, text_feat_val])
X_test_meta = np.hstack([X_test_meta, text_feat_test])

y_train = train_df["label_encoded"].values
y_val = val_df["prediction"].values

# Handle NaN
imputer = SimpleImputer(strategy='median')
X_train_meta = imputer.fit_transform(X_train_meta)
X_val_meta = imputer.transform(X_val_meta)
X_test_meta = imputer.transform(X_test_meta)

print(f"   Train meta shape: {X_train_meta.shape}")
print(f"   Val meta shape: {X_val_meta.shape}")

# ============================================================
# STEP 6: OPTIMIZED META-LEARNER
# ============================================================

print("\n" + "="*60)
print("Training Optimized Meta-Learner")
print("="*60)

# Strong class weights for Neutral
class_weights = compute_class_weight('balanced', classes=np.unique(y_train), y=y_train)
class_weights[0] *= 4.0  # 4x Neutral weight
class_weight_dict = {i: class_weights[i] for i in range(len(class_weights))}

print(f"   Class weights: Neutral={class_weights[0]:.2f}x")

# Random Forest with optimized params
rf = RandomForestClassifier(
    n_estimators=400,
    max_depth=10,
    min_samples_split=5,
    min_samples_leaf=2,
    class_weight=class_weight_dict,
    random_state=42,
    n_jobs=-1
)

# Gradient Boosting with optimized params
gb = GradientBoostingClassifier(
    n_estimators=250,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.8,
    random_state=42
)

# Logistic Regression with class weights
lr = LogisticRegression(
    C=1.5,
    max_iter=1000,
    class_weight=class_weight_dict,
    random_state=42,
    multi_class='multinomial',
    solver='lbfgs'
)

# Train all
rf.fit(X_train_meta, y_train)
gb.fit(X_train_meta, y_train)
lr.fit(X_train_meta, y_train)

# Optimized ensemble weights
rf_val_proba = rf.predict_proba(X_val_meta)
gb_val_proba = gb.predict_proba(X_val_meta)
lr_val_proba = lr.predict_proba(X_val_meta)

val_proba = (0.45 * rf_val_proba + 0.35 * gb_val_proba + 0.2 * lr_val_proba)
val_preds = np.argmax(val_proba, axis=1)

# ============================================================
# STEP 7: Validation
# ============================================================

print("\n" + "="*60)
print(" VALIDATION SCORE")
print("="*60)

val_pred_labels = label_encoder.inverse_transform(val_preds)
true_labels = val_df["prediction"].values

macro_f1 = f1_score(true_labels, val_pred_labels, average='macro')

print(f"\n{'='*60}")
print(f" MACRO F1: {macro_f1:.4f}")
print(f"{'='*60}")

print("\n Classification Report:")
print(classification_report(true_labels, val_pred_labels, digits=4))

# ============================================================
# STEP 8: Test Predictions
# ============================================================

print("\n" + "="*60)
print(" Generating Test Predictions")
print("="*60)

# Ensemble test predictions
rf_test_proba = rf.predict_proba(X_test_meta)
gb_test_proba = gb.predict_proba(X_test_meta)
lr_test_proba = lr.predict_proba(X_test_meta)

test_proba = (0.45 * rf_test_proba + 0.35 * gb_test_proba + 0.2 * lr_test_proba)
test_preds = np.argmax(test_proba, axis=1)

test_df["prediction"] = label_encoder.inverse_transform(test_preds)

print("\n Test Distribution:")
for label in label_encoder.classes_:
    count = (test_df["prediction"] == label).sum()
    percentage = count / len(test_df) * 100
    print(f"   {label:15s}: {count:4d} ({percentage:5.1f}%)")

# ============================================================
# STEP 9: Submission
# ============================================================

print("\n" + "="*60)
print("Creating Submission")
print("="*60)

submission_df = test_df[['id', 'prediction']].copy()
filename = f"submission_f1_{macro_f1:.4f}_final"

submission_df.to_csv(f"{filename}.csv", index=False, encoding='utf-8')
print(f"    Saved: {filename}.csv")

with zipfile.ZipFile(f"{filename}.zip", 'w', zipfile.ZIP_DEFLATED) as z:
    z.write(f"{filename}.csv")
print(f"   Saved: {filename}.zip")

============================================================
🚀 0.94+ MACRO F1 - FINAL OPTIMIZATION
============================================================

✅ Training data: 4901 samples (Neutral oversampled 3x)
✅ Labels: ['Neutral' 'Pro-Israel' 'Pro-Palestine']

============================================================
🔥 Training with 3-Fold Cross Validation
============================================================

============================================================
🔥 BERT with 3-Fold CV
============================================================
   Getting CV predictions...
   Fold 1/3

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

   Fold 2/3

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

   Fold 3/3

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

   Training final model...

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

   ✅ bert done

============================================================
🔥 ROBERTA with 3-Fold CV
============================================================
   Getting CV predictions...
   Fold 1/3

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

   Fold 2/3

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

   Fold 3/3

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

   Training final model...

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

   ✅ roberta done

============================================================
🔥 DEBERTA with 3-Fold CV
============================================================
   Getting CV predictions...
   Fold 1/3

Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

   Fold 2/3

Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

   Fold 3/3

Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

   Training final model...

Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

   ✅ deberta done

============================================================
🏗️ Creating Meta Features
============================================================
   Train meta shape: (4901, 19)
   Val meta shape: (210, 19)

============================================================
🎯 Training Optimized Meta-Learner
============================================================
   Class weights: Neutral=2.85x

============================================================
📊 VALIDATION SCORE
============================================================

============================================================
🎯 MACRO F1: 0.8905
============================================================

📋 Classification Report:
               precision    recall  f1-score   support

      Neutral     0.9206    0.8286    0.8722        70
   Pro-Israel     0.9286    0.9286    0.9286        70
Pro-Palestine     0.8312    0.9143    0.8707        70

     accuracy                         0.8905       210
    macro avg     0.8935    0.8905    0.8905       210
 weighted avg     0.8935    0.8905    0.8905       210


============================================================
🎯 Generating Test Predictions
============================================================

📊 Test Distribution:
   Neutral        :   56 ( 26.5%)
   Pro-Israel     :   71 ( 33.6%)
   Pro-Palestine  :   84 ( 39.8%)

============================================================
📁 Creating Submission
============================================================
   ✅ Saved: submission_f1_0.8905_final.csv
   ✅ Saved: submission_f1_0.8905_final.zip